const { DataTypes } = require("sequelize");
const sequelize = require("../config/database");

const Faculty = sequelize.define("Faculty", {
  id: { type: DataTypes.STRING(20), primaryKey: true },
  employeeNumber: { type: DataTypes.STRING(20), allowNull: false, unique: true },
  fullName: { type: DataTypes.STRING(100), allowNull: false },
  facultyStatus: { type: DataTypes.ENUM("Full-Time", "Part-Time"), defaultValue: "Full-Time" },
  position: { type: DataTypes.STRING(100) },
  sexAtBirth: { type: DataTypes.STRING(10) },
  civilStatus: { type: DataTypes.STRING(20) },
  nationality: { type: DataTypes.STRING(50) },
  religion: { type: DataTypes.STRING(50) },
  dateOfBirth: { type: DataTypes.DATEONLY },
  placeOfBirth: { type: DataTypes.STRING(100) },
  presentAddress: { type: DataTypes.TEXT },
  permanentAddress: { type: DataTypes.TEXT },
  primaryMobile: { type: DataTypes.STRING(20) },
  alternateMobile: { type: DataTypes.STRING(20) },
  primaryEmail: { type: DataTypes.STRING(100) },
  alternateEmail: { type: DataTypes.STRING(100) },
  college: { type: DataTypes.STRING(100) },
  department: { type: DataTypes.STRING(100) },
  employmentStartDate: { type: DataTypes.DATEONLY },
  employmentType: { type: DataTypes.STRING(50) },
  academicRank: { type: DataTypes.STRING(100) },
  bsDegree: { type: DataTypes.STRING(100) },
  bsMajor: { type: DataTypes.STRING(100) },
  bsUniversity: { type: DataTypes.STRING(100) },
  bsYear: { type: DataTypes.STRING(10) },
  msDegree: { type: DataTypes.STRING(100) },
  msMajor: { type: DataTypes.STRING(100) },
  msUniversity: { type: DataTypes.STRING(100) },
  msYear: { type: DataTypes.STRING(10) },
  phdDegree: { type: DataTypes.STRING(100) },
  phdMajor: { type: DataTypes.STRING(100) },
  phdUniversity: { type: DataTypes.STRING(100) },
  phdYear: { type: DataTypes.STRING(10) },
  specialization: { type: DataTypes.JSON },
  certifications: { type: DataTypes.JSON },
  subjects: { type: DataTypes.JSON },
  sections: { type: DataTypes.JSON },
  semester: { type: DataTypes.STRING(10) },
  academicYear: { type: DataTypes.STRING(20) },
  maxLoad: { type: DataTypes.INTEGER },
  currentLoad: { type: DataTypes.INTEGER },
  research: { type: DataTypes.JSON },
  adminRoles: { type: DataTypes.JSON },
  awards: { type: DataTypes.JSON },
  experience: { type: DataTypes.JSON },
  memberships: { type: DataTypes.JSON },
  photo: { type: DataTypes.TEXT },
}, {
  tableName: "faculty",
  timestamps: true,
});

module.exports = Faculty;
