const { DataTypes } = require("sequelize");
const sequelize = require("../config/database");

const Student = sequelize.define("Student", {
  id: { type: DataTypes.STRING(20), primaryKey: true },
  studentNumber: { type: DataTypes.STRING(20), allowNull: false, unique: true },
  fullName: { type: DataTypes.STRING(100), allowNull: false },
  status: { type: DataTypes.ENUM("Regular", "Irregular", "Transferee", "Returnee"), defaultValue: "Regular" },
  course: { type: DataTypes.STRING(10) },
  year: { type: DataTypes.INTEGER },
  section: { type: DataTypes.STRING(20) },
  gpa: { type: DataTypes.DECIMAL(3, 2) },
  sexAtBirth: { type: DataTypes.STRING(10) },
  civilStatus: { type: DataTypes.STRING(20) },
  nationality: { type: DataTypes.STRING(50) },
  religion: { type: DataTypes.STRING(50) },
  dateOfBirth: { type: DataTypes.DATEONLY },
  placeOfBirth: { type: DataTypes.STRING(100) },
  presentAddress: { type: DataTypes.TEXT },
  permanentAddress: { type: DataTypes.TEXT },
  primaryMobile: { type: DataTypes.STRING(20) },
  alternateMobile: { type: DataTypes.STRING(20) },
  primaryEmail: { type: DataTypes.STRING(100) },
  alternateEmail: { type: DataTypes.STRING(100) },
  fatherName: { type: DataTypes.STRING(100) },
  fatherOccupation: { type: DataTypes.STRING(100) },
  fatherDOB: { type: DataTypes.DATEONLY },
  motherName: { type: DataTypes.STRING(100) },
  motherOccupation: { type: DataTypes.STRING(100) },
  motherDOB: { type: DataTypes.DATEONLY },
  siblings: { type: DataTypes.STRING(5) },
  familyIncome: { type: DataTypes.STRING(50) },
  guardianName: { type: DataTypes.STRING(100) },
  guardianRelation: { type: DataTypes.STRING(50) },
  guardianContact: { type: DataTypes.STRING(20) },
  lastSchool: { type: DataTypes.STRING(100) },
  lastYearAttended: { type: DataTypes.STRING(20) },
  lrn: { type: DataTypes.STRING(20) },
  honors: { type: DataTypes.STRING(50) },
  college: { type: DataTypes.STRING(100) },
  program: { type: DataTypes.STRING(100) },
  curriculum: { type: DataTypes.STRING(50) },
  yearLevel: { type: DataTypes.STRING(20) },
  residency: { type: DataTypes.STRING(20) },
  photo: { type: DataTypes.TEXT },
}, {
  tableName: "students",
  timestamps: true,
});

module.exports = Student;
